import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const cfg=window.SYSTEM_CONFIG||{},app=document.getElementById("app");
const supabase=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
let session=null,state={view:"home",workbooks:[],answers:[],brain:[],ideas:[],progress:{},wb:null,sections:[],si:0,questions:[],summary:null};
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const hero=(tag,title,p="")=>`<div class="hero"><div class="tag">${tag}</div><h1>${title}</h1>${p?`<p>${p}</p>`:""}</div>`;
const route=()=>location.hash.replace(/^#\/?/,"")||"home",go=r=>location.hash="#/"+r;
function nav(r,l,a){return `<button data-route="${r}" class="${a===r?"active":""}"><span>${l}</span><span>↗</span></button>`}
function shell(content,a=state.view){const x=Object.values(state.progress),d=x.reduce((s,v)=>s+v.done,0),t=x.reduce((s,v)=>s+v.total,0),p=t?Math.round(d/t*100):0;return `<div class="shell"><aside class="sidebar"><div class="sideLogo">SYSTEM<sup>©</sup></div><div class="sideUser">${esc(session?.user?.email||"")}</div><div class="nav">${nav("home","HOME",a)}${nav("workbooks","WORKBOOKS",a)}${nav("brain","MY BRAIN",a)}${nav("ideas","IDEA VAULT",a)}${nav("search","SEARCH",a)}${nav("settings","SETTINGS",a)}</div><div class="progressBox"><div class="progressLabel"><span>COURSE PROGRESS</span><span>${p}%</span></div><div class="progressTrack"><div class="progressFill" style="width:${p}%"></div></div></div></aside><main><div class="topline"><span>PRIVATE BLOG OS / SASHA</span><span>${new Date().toLocaleDateString("ru-RU",{day:"2-digit",month:"short"})}</span></div>${content}</main></div>`}
function bind(){document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>go(b.dataset.route));const o=document.getElementById("logout");if(o)o.onclick=()=>supabase.auth.signOut()}
async function init(){const {data}=await supabase.auth.getSession();session=data.session;supabase.auth.onAuthStateChange((_e,s)=>{session=s;s?boot():renderAuth()});session?boot():renderAuth()}
function renderAuth(){app.innerHTML=`<div class="auth"><div class="authCard"><div class="logo">SYSTEM<sup>©</sup></div><div class="kicker">PRIVATE WORKSPACE / SASHA</div><h1>Твой блог.<br>Твоя система.</h1><div id="msg"></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Password</label><input id="password" type="password"></div><div class="row"><button class="btn" id="login">SIGN IN</button><button class="btn secondary" id="signup">CREATE ACCOUNT</button></div></div></div>`;document.getElementById("login").onclick=()=>auth(false);document.getElementById("signup").onclick=()=>auth(true)}
async function auth(up){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,r=up?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});document.getElementById("msg").innerHTML=r.error?`<div class="error">${esc(r.error.message)}</div>`:up&&!r.data.session?`<div class="success">Account created. Check email if confirmation is enabled.</div>`:""}
async function boot(){await load();await routeTo(route());window.onhashchange=()=>routeTo(route())}
async function load(){const uid=session.user.id,[w,a,b,i,q]=await Promise.all([supabase.from("workbooks").select("*").eq("user_id",uid).order("position"),supabase.from("answers").select("question_id,value").eq("user_id",uid),supabase.from("brain_entries").select("*").eq("user_id",uid).order("updated_at",{ascending:false}),supabase.from("ideas").select("*").eq("user_id",uid).order("created_at",{ascending:false}).limit(5000),supabase.from("questions").select("id,workbook_id").eq("user_id",uid)]);state.workbooks=w.data||[];state.answers=a.data||[];state.brain=b.data||[];state.ideas=i.data||[];const amap=new Map(state.answers.map(x=>[x.question_id,x.value]));for(const wb of state.workbooks){const all=(q.data||[]).filter(x=>x.workbook_id===wb.id),done=all.filter(x=>(amap.get(x.id)||"").trim()).length;state.progress[wb.id]={done,total:all.length,pct:all.length?Math.round(done/all.length*100):0}}}
async function routeTo(r){if(r.startsWith("workbook/"))return openWorkbook(r.split("/")[1]);state.view=r;render()}
function render(){if(state.view==="workbooks")return renderWorkbooks();if(state.view==="brain")return renderBrain();if(state.view==="ideas")return renderIdeas();if(state.view==="search")return renderSearch();if(state.view==="settings")return renderSettings();renderHome()}
function card(w){const p=state.progress[w.id]||{pct:0,done:0,total:0};return `<div class="card clickable" data-wb="${esc(w.slug)}" style="border-top:10px solid ${esc(w.accent||"#111")}"><div class="cardTop"><span>${String(w.position||0).padStart(2,"0")}</span><span>${p.pct}%</span></div><h3>${esc(w.title)}</h3><p>${esc(w.subtitle||"")}</p><div class="meter"><span style="width:${p.pct}%"></span></div><p style="margin-top:7px">${p.done}/${p.total} answers</p></div>`}
function hookCards(){document.querySelectorAll("[data-wb]").forEach(x=>x.onclick=()=>go("workbook/"+x.dataset.wb))}
function renderHome(){const inProgress=state.workbooks.filter(w=>{const p=state.progress[w.id];return p&&p.done>0&&p.pct<100}).slice(0,4);app.innerHTML=shell(`${hero("YOUR BLOG SYSTEM","Собери блог<br>из своих мыслей.","Все ответы, summaries и идеи становятся долговременной памятью для AI.")}<div class="panel"><div class="panelTitle"><h2>ASK MY BRAIN</h2><span class="small">uses saved memory</span></div><div class="askBox"><textarea id="ask" placeholder="Например: дай мне 1000 идей Reels на основе всего, что ты знаешь обо мне"></textarea><button class="iconBtn" id="askMic">🎙</button><button class="btn blue" id="askBtn">ASK</button></div><div id="askOut"></div></div><div class="panelTitle homeProgressTitle"><h2>В ПРОЦЕССЕ</h2><span class="small">незавершённые workbook'и</span></div>${inProgress.length?`<div class="grid2">${inProgress.map(card).join("")}</div>`:`<div class="notice">Здесь появятся workbook'и, которые ты начнёшь заполнять. Все материалы находятся в WORKBOOKS.</div>`}`,"home");bind();hookCards();document.getElementById("askBtn").onclick=askBrain;document.getElementById("askMic").onclick=()=>voice(document.getElementById("ask"),document.getElementById("askMic"))}
async function askBrain(){const el=document.getElementById("ask"),out=document.getElementById("askOut"),text=el.value.trim();if(!text)return;const m=text.match(/\b(\d+)\s*(?:ид\w*|ideas?)\b/i);if(m&&Number(m[1])>=50)return generateIdeas(Number(m[1]),text,out);out.innerHTML=`<div class="answerBox"><span class="loader"></span>Ищу по твоей памяти…</div>`;try{const d=await ai({action:"chat",message:text});out.innerHTML=`<div class="answerBox">${esc(d.answer||"").replace(/\n/g,"<br>")}${chips(d.sources||[])}</div>`}catch(e){out.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function renderWorkbooks(){app.innerHTML=shell(`${hero("WORKBOOK LIBRARY","Твои<br>воркбуки.","Каждая секция — отдельная страница. Всё сохраняется автоматически.")}<div class="grid2">${state.workbooks.map(card).join("")||`<div class="notice">Workbooks ещё не загружены.</div>`}</div>`,"workbooks");bind();hookCards()}
async function openWorkbook(slug){state.wb=state.workbooks.find(w=>w.slug===slug);if(!state.wb)return go("workbooks");const {data}=await supabase.from("sections").select("*").eq("user_id",session.user.id).eq("workbook_id",state.wb.id).order("position");state.sections=data||[];state.si=0;await loadSection();renderWorkbook()}
async function loadSection(){const s=state.sections[state.si];if(!s)return;const [q,sm]=await Promise.all([supabase.from("questions").select("*").eq("user_id",session.user.id).eq("section_id",s.id).order("position"),supabase.from("section_summaries").select("*").eq("user_id",session.user.id).eq("section_id",s.id).maybeSingle()]);state.questions=q.data||[];state.summary=sm.data||null}
const ans=id=>state.answers.find(a=>a.question_id===id)?.value||"";
function renderWorkbook(){const w=state.wb,s=state.sections[state.si];if(!w||!s)return;app.innerHTML=shell(`<div class="sheet"><div class="sheetHead"><div class="eyebrow">WORKBOOK / ${esc(w.title)} · ${(state.progress[w.id]||{}).pct||0}% COMPLETE</div><h2>${esc(w.title)}</h2><div class="pageNav"><button class="btn secondary" id="prev" ${state.si===0?"disabled":""}>← PREV</button><select id="sel">${state.sections.map((x,i)=>`<option value="${i}" ${i===state.si?"selected":""}>${i+1}/${state.sections.length} · ${esc(x.title)}</option>`).join("")}</select><button class="btn secondary" id="next" ${state.si===state.sections.length-1?"disabled":""}>NEXT →</button></div></div><div class="section"><div class="sectionTitle">${esc(s.title)}</div><div class="sectionDesc">${esc(s.description||"")}</div>${state.questions.map((q,i)=>`<div class="question"><div class="questionLabel">${i+1}. ${esc(q.prompt)}</div>${q.help_text?`<div class="help">${esc(q.help_text)}</div>`:""}<div class="answerWrap"><textarea data-q="${q.id}" placeholder="Твой ответ…">${esc(ans(q.id))}</textarea><button class="mic" data-mic="${q.id}">🎙</button></div><div class="saveState" id="s-${q.id}">${ans(q.id)?"saved":""}</div></div>`).join("")}<div class="row"><button class="btn yellow" id="sumPage">SUMMARIZE THIS PAGE</button>${state.si===state.sections.length-1?`<button class="btn" id="sumWb">SUMMARIZE WHOLE WORKBOOK</button>`:""}</div><div id="sumOut">${summaryHTML(state.summary)}</div></div></div>`,"workbooks");bind();document.getElementById("prev").onclick=()=>move(-1);document.getElementById("next").onclick=()=>move(1);document.getElementById("sel").onchange=async e=>{state.si=Number(e.target.value);await loadSection();renderWorkbook()};document.querySelectorAll("textarea[data-q]").forEach(t=>t.oninput=()=>saveLater(t.dataset.q,t.value));document.querySelectorAll("[data-mic]").forEach(b=>b.onclick=()=>voice(document.querySelector(`textarea[data-q="${b.dataset.mic}"]`),b));document.getElementById("sumPage").onclick=summarizePage;const wb=document.getElementById("sumWb");if(wb)wb.onclick=summarizeWorkbook}
async function move(d){state.si=Math.max(0,Math.min(state.sections.length-1,state.si+d));await loadSection();renderWorkbook();scrollTo(0,0)}
const timers=new Map();function saveLater(id,value){document.getElementById("s-"+id).textContent="saving…";clearTimeout(timers.get(id));timers.set(id,setTimeout(()=>saveAnswer(id,value),600))}
async function saveAnswer(id,value){const {error}=await supabase.from("answers").upsert({user_id:session.user.id,question_id:id,value},{onConflict:"user_id,question_id"});document.getElementById("s-"+id).textContent=error?"save failed":"saved";const x=state.answers.find(a=>a.question_id===id);x?x.value=value:state.answers.push({question_id:id,value});ai({action:"index_answer",question_id:id}).catch(()=>{})}
function summaryHTML(s){if(!s)return"";const a=s.analysis||{};return `<div class="summaryBox"><h3>AI PAGE SUMMARY</h3>${esc(s.summary||"").replace(/\n/g,"<br>")}${["key_insights","patterns","content_angles","contradictions","memorable_phrases"].map(k=>Array.isArray(a[k])&&a[k].length?`<p><b>${k.replaceAll("_"," ").toUpperCase()}</b><br>${a[k].map(x=>"• "+esc(x)).join("<br>")}</p>`:"").join("")}</div>`}
async function summarizePage(){const out=document.getElementById("sumOut");out.innerHTML=`<div class="notice"><span class="loader"></span>Analysing…</div>`;try{const d=await ai({action:"summarize_section",section_id:state.sections[state.si].id});state.summary=d.summary;out.innerHTML=summaryHTML(d.summary)}catch(e){out.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function summarizeWorkbook(){const out=document.getElementById("sumOut");try{const d=await ai({action:"summarize_workbook",workbook_id:state.wb.id});out.insertAdjacentHTML("beforeend",`<div class="success">MY BRAIN updated: ${d.brain_count||0} entries.</div>`);await load()}catch(e){out.insertAdjacentHTML("beforeend",`<div class="error">${esc(e.message)}</div>`)}}
function chips(a){return a?.length?`<div class="sources">${a.map(x=>`<span class="sourceChip">${esc(x.source_label||x.source_key||"source")}</span>`).join("")}</div>`:""}
function renderBrain(){const g={};for(const x of state.brain)(g[x.category||"OTHER"]??=[]).push(x);app.innerHTML=shell(`${hero("AI MEMORY","MY BRAIN","Собранные AI-выводы из твоих реальных ответов.")}${Object.keys(g).length?Object.entries(g).map(([k,v])=>`<div class="brainGroup"><h2>${esc(k.replaceAll("_"," "))}</h2>${v.map(x=>`<div class="brainEntry"><h4>${esc(x.title)}</h4><div>${esc(x.content)}</div></div>`).join("")}</div>`).join(""):`<div class="notice">Пока пусто. Сначала заполни и summarize workbook.</div>`}`,"brain");bind()}
function renderIdeas(){app.innerHTML=shell(`${hero("CAPTURE + GENERATE","IDEA<br>VAULT","Можно сохранять свои мысли и генерировать любое количество идей.")}<div class="panel"><div class="askBox"><textarea id="idea" placeholder="Скажи или напиши идею…"></textarea><button class="iconBtn" id="ideaMic">🎙</button><button class="btn" id="saveIdea">SAVE</button></div></div><div class="panel"><div class="row"><input id="count" type="number" min="1" value="20" style="width:110px;padding:12px;border:1px solid #111"><input id="brief" placeholder="Reels / lifestyle / всё" style="flex:1;padding:12px;border:1px solid #111"><button class="btn blue" id="gen">GENERATE</button></div><div id="genOut"></div></div><div class="panel"><div class="panelTitle"><h2>ALL IDEAS</h2><span>${state.ideas.length}</span></div>${state.ideas.map(i=>`<div class="idea"><div class="ideaMeta">${esc(i.origin||"manual")}</div><h4>${esc(i.title)}</h4><div>${esc(i.body||"").replace(/\n/g,"<br>")}</div></div>`).join("")||`<div class="small">Пока пусто.</div>`}</div>`,"ideas");bind();document.getElementById("ideaMic").onclick=()=>voice(document.getElementById("idea"),document.getElementById("ideaMic"));document.getElementById("saveIdea").onclick=async()=>{const e=document.getElementById("idea"),t=e.value.trim();if(!t)return;await supabase.from("ideas").insert({user_id:session.user.id,title:t.slice(0,120),body:t,origin:"manual",status:"new"});await load();renderIdeas()};document.getElementById("gen").onclick=()=>generateIdeas(Math.max(1,Number(document.getElementById("count").value)||20),document.getElementById("brief").value||"content ideas",document.getElementById("genOut"))}
async function generateIdeas(n,brief,out){let done=0,avoid=[];try{while(done<n){out.innerHTML=`<div class="notice"><span class="loader"></span>${done}/${n}</div>`;const d=await ai({action:"generate_ideas",count:Math.min(50,n-done),brief,avoid_titles:avoid.slice(-120)}),a=d.ideas||[];if(!a.length)break;done+=a.length;avoid.push(...a.map(x=>x.title))}await load();out.innerHTML=`<div class="success">Generated and saved ${done} ideas.</div>`}catch(e){out.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function renderSearch(){app.innerHTML=shell(`${hero("SEMANTIC SEARCH","SEARCH","Ищи по смыслу во всех своих ответах и summaries.")}<div class="panel"><div class="askBox"><input id="search" placeholder="Например: страх проявляться"><button class="btn blue" id="searchBtn">SEARCH</button></div><div id="searchOut"></div></div>`,"search");bind();document.getElementById("searchBtn").onclick=async()=>{const q=document.getElementById("search").value.trim(),out=document.getElementById("searchOut");if(!q)return;try{const d=await ai({action:"search",query:q});out.innerHTML=(d.results||[]).map(x=>`<div class="searchResult"><b>${esc(x.source_label||"")}</b><br>${esc(x.content||"")}</div>`).join("")||`<div class="notice">Nothing found yet.</div>`}catch(e){out.innerHTML=`<div class="error">${esc(e.message)}</div>`}}}
function renderSettings(){app.innerHTML=shell(`${hero("ACCOUNT","SETTINGS","Твой закрытый workspace.")}<div class="panel"><p>${esc(session.user.email||"")}</p><button class="btn secondary" id="logout">SIGN OUT</button></div>`,"settings");bind()}
async function ai(body){const {data,error}=await supabase.functions.invoke("ai",{body});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data}
async function voice(target,button){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const r=new SR();r.lang="ru-RU";r.interimResults=true;const base=target.value.trim();button.classList.add("listening");r.onresult=e=>{let t="";for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;target.value=(base?base+" ":"")+t;target.dispatchEvent(new Event("input",{bubbles:true}))};r.onend=r.onerror=()=>button.classList.remove("listening");return r.start()}alert("Use your phone/keyboard system dictation in this browser.")}
init();